# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.13.0'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run test
    npm run build
  displayName: 'npm install, test and build'

- task: DownloadSecureFile@1
  name: mySqlCertificate
  inputs:
    secureFile: 'BaltimoreCyberTrustRoot.crt.pem'

- task: CopyFiles@2
  displayName: 'Copy dist folder'
  inputs:
    SourceFolder: 'dist'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/dist/dist'

- task: CopyFiles@2
  displayName: 'Copy node_modules folder'
  inputs:
    SourceFolder: 'node_modules'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/dist/node_modules'

- task: CopyFiles@2
  displayName: 'Copy .json, .env and .sequelizerc'
  inputs:
    Contents: |
      *.env
      *.json
      *.sequelizerc
    TargetFolder: '$(Build.ArtifactStagingDirectory)/dist'

- task: CopyFiles@2
  displayName: 'Copy MySQL Certificate'
  inputs:
    SourceFolder: '$(Agent.TempDirectory)'
    Contents: '*.pem'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/dist'

- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/dist'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: DeleteFiles@1
  displayName: 'Delete temp directory'
  inputs:
    SourceFolder: '$(Build.ArtifactStagingDirectory)'
    Contents: 'dist'

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
